apiVersion: v1
kind: Service
metadata:
  name: campus-backend-service
spec:
  type: NodePort
  selector:
    app: campus-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30050
      